//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_types")]
pub enum AccountTypes {
    #[sea_orm(string_value = "checking")]
    Checking,
    #[sea_orm(string_value = "saving")]
    Saving,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "interest_frequency_units"
)]
pub enum InterestFrequencyUnits {
    #[sea_orm(string_value = "day")]
    Day,
    #[sea_orm(string_value = "month")]
    Month,
    #[sea_orm(string_value = "week")]
    Week,
    #[sea_orm(string_value = "year")]
    Year,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_categories"
)]
pub enum TransactionCategories {
    #[sea_orm(string_value = "dividend")]
    Dividend,
    #[sea_orm(string_value = "expense")]
    Expense,
    #[sea_orm(string_value = "income")]
    Income,
    #[sea_orm(string_value = "interest")]
    Interest,
    #[sea_orm(string_value = "transfer")]
    Transfer,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "transaction_types")]
pub enum TransactionTypes {
    #[sea_orm(string_value = "deposit")]
    Deposit,
    #[sea_orm(string_value = "expense")]
    Expense,
    #[sea_orm(string_value = "transfer")]
    Transfer,
    #[sea_orm(string_value = "withdraw")]
    Withdraw,
}
